### ISSUE TITLE
Current status of this provider?

### ISSUE THREAD

**Issue by hollow** [Leaseweb/terraform-provider-leaseweb#47]
We currently use v0.4.1 of this provider to import, manage and reinstall dedicated servers. Unfortunately, the provider runs into a timeout when importing private rack servers that don't have all the information available (e.g. list of IPs, remote management, etc.). I wanted to look into upgrading to the latest version and attempt a fix for this issue and then realized that the v1.*-alpha versions of this provider don't even contain resources for dedicated servers anymore. I hope this is not this provider's desired direction, which would render it useless for our purposes.

**Comment by nrocco** [comment]
@hollow thanks for your feedback. Rest assured that the v1 will certainly contain all the resources for dedicated servers. The team is currently bringing this back as we speak. 

We don't have a clear ETA for the next release, yet. 

Do you mind to share some more detailed info about your timeout issue (via Leaseweb Customer Portal) so we can look into that in parallel of the terraform plugin development. 

Thanks
